=== blanconuclear/LinguaxesDeMarcas/2ªevaluación/xml/probas-examen-xml/xsd/ex2/efemerides.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="efemerides">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="efemeride" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fecha" type="xs:string"></xs:element>
                            <xs:element name="hecho" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== blanconuclear/LinguaxesDeMarcas/2ªevaluación/xml/probas-examen-xml/xsd/ex2/ex2.xml
<?xml version="1.0" encoding="UTF-8"?>
<efemerides
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="efemerides.xsd">
    <efemeride>
        <fecha>20 de julio de 1969</fecha>
        <hecho>Llegada del hombre a la Luna</hecho>
    </efemeride>
    <efemeride>
        <fecha>12 de octubre de 1492</fecha>
        <hecho>Llegada de Colón a América</hecho>
    </efemeride>
    <efemeride>
        <fecha>6 de abril de 1909</fecha>
        <hecho>llegada de Robert Peary al Polo Norte</hecho>
    </efemeride>
</efemerides>
