=== blanconuclear/LinguaxesDeMarcas/2ªevaluación/xml/probas-examen-xml/xsd/ex1/ex8.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="agenda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="contacto" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="telefonoFijo" type="xs:int" maxOccurs="unbounded"
                                minOccurs="0"></xs:element>
                            <xs:element name="telefonoMovil" type="xs:int"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== blanconuclear/LinguaxesDeMarcas/2ªevaluación/xml/probas-examen-xml/xsd/ex1/ex8.xml
<?xml version="1.0" encoding="UTF-8"?>
<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchemainstance"
    xsi:noNamespaceSchemaLocation="ex8.xsd">
    <contacto>
        <nombre>Ayuntamiento</nombre>
        <telefonoFijo>010</telefonoFijo>
        <telefonoMovil></telefonoMovil>
    </contacto>
    <contacto>
        <nombre>Emergencias</nombre>
        <telefonoFijo>112 (Uni√≥n Europea)</telefonoFijo>
        <telefonoFijo>911 (Estados Unidos)</telefonoFijo>
        <telefonoMovil>Desconocido</telefonoMovil>
    </contacto>
</agenda>
