<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE actividades [
    <!ELEMENT actividades (evento)>
    <!ELEMENT evento (actividad*,otraEtiqueta*)>
    <!ELEMENT actividad (#PCDATA)>
    <!ATTLIST actividad fecha CDATA #REQUIRED>
    <!ATTLIST actividad hora CDATA #REQUIRED>
    <!ATTLIST actividad lugar CDATA #REQUIRED>
    <!ELEMENT otraEtiqueta (#PCDATA)>
]>


<actividades
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="actividades.xsd">
    <evento>
        <actividad fecha="10 de abril de 2024" hora="9:00" lugar="Oficina">
            Reunión de equipo
        </actividad>
        <actividad fecha="12 de abril de 2024" hora="14:00" lugar="Sala de conferencias">
            Presentación del proyecto
        </actividad>
        <otraEtiqueta>Contenido de otra etiqueta</otraEtiqueta>
    </evento>
</actividades>