=== blanconuclear/LinguaxesDeMarcas/2ªevaluación/examen xml/ex1/universidad.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="universidad">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="campus" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="edificio" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"></xs:element>
                                        <xs:element name="departamento-academico" type="xs:string"></xs:element>
                                        <xs:element name="habitacion">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="numero" type="xs:string"
                                                            use="required"></xs:attribute>
                                                        <xs:attribute name="capacidad"
                                                            type="xs:string" use="required"></xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="cod" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== blanconuclear/LinguaxesDeMarcas/2ªevaluación/examen xml/ex1/universidad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE universidad [
    <!ELEMENT universidad (campus+)>
    <!ATTLIST campus cod CDATA #REQUIRED>
    <!ELEMENT campus (edificio+)>
    <!ELEMENT edificio (nombre,departamento-academico,habitacion+)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT departamento-academico (#PCDATA)>
    <!ELEMENT habitacion (#PCDATA)>
    <!ATTLIST habitacion numero CDATA #REQUIRED>
    <!ATTLIST habitacion capacidad CDATA #REQUIRED>
]>

<universidad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="universidad.xsd">
    <campus cod="USC">
        <edificio>
            <nombre>Don Ramón</nombre>
            <departamento-academico>Filosofía</departamento-academico>
            <habitacion numero="01" capacidad="10" />
        </edificio>
        <edificio>
            <nombre>Perez Sanchez</nombre>
            <departamento-academico>Matemáticas</departamento-academico>
            <habitacion numero="02" capacidad="20" />
        </edificio>
    </campus>
    <campus cod="UDV">
        <edificio>
            <nombre>Tijuana</nombre>
            <departamento-academico>Literatura</departamento-academico>
            <habitacion numero="03" capacidad="15" />
        </edificio>
        <edificio>
            <nombre>Campestre</nombre>
            <departamento-academico>Derecho</departamento-academico>
            <habitacion numero="04" capacidad="8" />
        </edificio>
    </campus>
</universidad>
